"""
WeBrain Evolution Engine — Phase 2 激活版
Skill 记录生成 + 真实改进建议 + 新模式发现
"""

import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import httpx

logger = logging.getLogger("webrain.evolution")


class EvolutionEngine:
    """Self-evolution engine with real skill tracking and LLM-powered analysis."""

    def __init__(self, memory_manager: Any, llm_config: Optional[Dict] = None):
        self.memory = memory_manager
        self.llm_config = llm_config or {
            "base_url": "http://localhost:1234/v1",
            "model_id": "minimax/minimax-m2.7",
        }

    async def run_cycle(self, agent_id: str, focus_area: str = "general") -> Dict[str, Any]:
        """Run one evolution cycle with real analysis."""
        cycle_id = f"evo-{datetime.now(timezone.utc).timestamp():.0f}"
        logger.info(f"Starting evolution cycle {cycle_id} for agent {agent_id}")

        # 1. Analyze skill performance
        skills = await self.memory.get_skills(limit=100)
        improvements = []

        for skill in skills:
            total = skill.get("success_count", 0) + skill.get("failure_count", 0)
            if total == 0:
                continue
            rate = skill["success_count"] / total

            if rate < 0.3:
                suggestion = f"成功率 {rate*100:.0f}% 过低。建议重写触发模式或模板。"
                confidence = 30
            elif rate < 0.6:
                suggestion = f"成功率 {rate*100:.0f}% 一般。建议优化模板匹配逻辑。"
                confidence = 55
            elif rate < 0.8:
                suggestion = f"成功率 {rate*100:.0f}% 良好。可考虑添加更多变体触发词。"
                confidence = 75
            else:
                continue

            improvements.append({
                "skillId": skill["id"],
                "skillName": skill["name"],
                "suggestion": suggestion,
                "confidence": confidence,
                "currentRate": rate,
            })

        # 2. LLM-powered pattern analysis from recent memories
        recent = await self.memory.get_recent(level="L2", limit=50)
        new_patterns = await self._discover_patterns(recent)

        # 3. Auto-generate skills from high-frequency patterns
        auto_skills = await self._auto_generate_skills(recent)

        logger.info(f"Evolution cycle {cycle_id} completed: {len(improvements)} improvements, {len(new_patterns)} patterns, {len(auto_skills)} auto-skills")

        return {
            "cycleId": cycle_id,
            "appliedAt": datetime.now(timezone.utc).isoformat(),
            "improvements": improvements,
            "newPatterns": new_patterns,
            "autoSkills": auto_skills,
            "stats": {
                "totalSkills": len(skills),
                "improvedSkills": len(improvements),
                "totalPatterns": len(new_patterns),
                "autoGeneratedSkills": len(auto_skills),
            },
        }

    async def _discover_patterns(self, memories: List[Dict]) -> List[Dict]:
        """Use LLM to discover patterns from recent memories."""
        if len(memories) < 5:
            return []

        texts = "\n".join([f"- {m.get('content', '')}" for m in memories[:20]])
        prompt = f"""分析以下用户对话记录，发现重复出现的模式或主题。
以JSON返回：{{"patterns": [{{"pattern": "模式描述", "frequency": 次数, "description": "详细说明"}}]}}

记录：
{texts}"""

        try:
            result = await self._llm_call([
                {"role": "system", "content": "你是一个模式发现专家。"},
                {"role": "user", "content": prompt},
            ], max_tokens=1024)
            content = result["choices"][0]["message"]["content"]
            json_str = content
            if "```" in content:
                json_str = content.split("```")[1].split("```")[0].strip()
            parsed = json.loads(json_str)
            return parsed.get("patterns", [])
        except Exception as e:
            logger.warning(f"Pattern discovery failed: {e}")
            return []

    async def _auto_generate_skills(self, memories: List[Dict]) -> List[Dict]:
        """Auto-generate skill records from memory patterns."""
        # Count trigger words
        word_freq: Dict[str, int] = {}
        for mem in memories:
            content = mem.get("content", "").lower()
            words = content.split()
            for w in words:
                w = w.strip(".,!?;:()")
                if len(w) > 3 and w not in ("这个", "那个", "什么", "怎么", "可以", "用户"):
                    word_freq[w] = word_freq.get(w, 0) + 1

        new_skills = []
        import sqlite3
        from pathlib import Path
        db_path = str(Path.home() / ".webrain" / "memory.db")
        conn = sqlite3.connect(db_path)
        for w, f in sorted(word_freq.items(), key=lambda x: x[1], reverse=True)[:5]:
            if f >= 3:
                # Check if skill already exists
                row = conn.execute("SELECT id FROM skills WHERE trigger_pattern = ?", (w,)).fetchone()
                if not row:
                    skill_id = f"skill-{datetime.now(timezone.utc).timestamp():.0f}-{w[:8]}"
                    conn.execute(
                        "INSERT INTO skills (id, name, description, trigger_pattern, template, created_at) VALUES (?, ?, ?, ?, ?, ?)",
                        (skill_id, f"处理 '{w}' 请求", f"自动生成的技能：处理包含 '{w}' 的用户请求", w, f"使用相关工具处理 {w} 请求", datetime.now(timezone.utc).isoformat()),
                    )
                    new_skills.append({"id": skill_id, "name": f"处理 '{w}'", "trigger": w, "frequency": f})
        conn.commit()
        conn.close()
        return new_skills

    async def record_skill_invocation(self, skill_name: str, success: bool) -> None:
        """Record a skill invocation result."""
        import sqlite3
        from pathlib import Path
        db_path = str(Path.home() / ".webrain" / "memory.db")
        conn = sqlite3.connect(db_path)
        row = conn.execute("SELECT id, success_count, failure_count FROM skills WHERE name = ?", (skill_name,)).fetchone()
        if row:
            if success:
                conn.execute("UPDATE skills SET success_count = success_count + 1, updated_at = ? WHERE id = ?",
                    (datetime.now(timezone.utc).isoformat(), row["id"]))
            else:
                conn.execute("UPDATE skills SET failure_count = failure_count + 1, updated_at = ? WHERE id = ?",
                    (datetime.now(timezone.utc).isoformat(), row["id"]))
            conn.commit()
        conn.close()

    async def get_stats(self) -> Dict[str, Any]:
        skills = await self.memory.get_skills(limit=1000)
        total_success = sum(s.get("success_count", 0) for s in skills)
        total_failure = sum(s.get("failure_count", 0) for s in skills)
        total = total_success + total_failure

        return {
            "totalSkills": len(skills),
            "totalInvocations": total,
            "overallSuccessRate": total_success / total if total > 0 else 0,
            "averageSkillSuccessRate": sum(
                s.get("success_count", 0) / max(s.get("success_count", 0) + s.get("failure_count", 0), 1)
                for s in skills
            ) / max(len(skills), 1),
        }

    async def _llm_call(self, messages: List[Dict], max_tokens: int = 1024) -> Dict[str, Any]:
        url = self.llm_config["base_url"].rstrip("/") + "/chat/completions"
        payload = {
            "model": self.llm_config["model_id"],
            "messages": messages,
            "temperature": 0.5,
            "max_tokens": max_tokens,
        }
        headers = {"Content-Type": "application/json"}
        if self.llm_config.get("api_key"):
            headers["Authorization"] = f"Bearer {self.llm_config['api_key']}"
        async with httpx.AsyncClient(timeout=60.0) as client:
            resp = await client.post(url, json=payload, headers=headers)
            resp.raise_for_status()
            return resp.json()
